FROM golang:1.24-alpine AS builder

WORKDIR /build

COPY pkg/ pkg/
COPY services/ services/

WORKDIR /build/services/auth
RUN CGO_ENABLED=0 GOOS=linux go build -o /app/server .

FROM alpine:3.20
RUN apk --no-cache add ca-certificates tzdata
WORKDIR /app
COPY --from=builder /app/server .
EXPOSE 3001
CMD ["./server"]
